[package]
name = "tg-voting"
version = "0.0.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
dotenv = "0.15.0"
env = "1.0.1"
poise = "0.6.2"
serde = { version = "1.0.229", features = ["derive"] }
serenity = "0.12.5"
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "tls-rustls-ring"] }
tokio = {version = "1.53.1", features = ["rt-multi-thread", "macros"]}
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
